name = 'PRC'
longname = 'AUTOCONVERSION DROPLETS'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRA'
longname = 'ACCRETION DROPLETS BY RAIN'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PSMLT'
longname = 'CHANGE Q MELTING SNOW TO RAIN'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'EVPMS'
longname = 'CHNAGE Q MELTING SNOW EVAPORATING'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRACS'
longname = 'CHANGE Q RAIN-SNOW COLLECTION'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'EVPMG'
longname = 'CHANGE Q MELTING OF GRAUPEL AND EVAPORATION'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRACG'
longname = 'CHANGE IN Q COLLECTION RAIN BY GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRE'
longname = 'EAPORATION OF RAIN'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PGMLT'
longname = 'CHANGE Q MELTING OF GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'MNUCCC'
longname = 'CHANGE Q DUE TO CONTACT FREEZ DROPLETS'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PSACWS'
longname = 'CHANGE Q DROPLET ACCRETION BY SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PSACWI'
longname = 'CHANGE Q DROPLET ACCRETION BY CLOUD ICE'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QMULTS'
longname = 'CHANGE Q DUE TO ICE MULT DROPLETS/SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QMULTG'
longname = 'CHANGE Q DUE TO ICE MULT DROPLETS/GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PSACWG'
longname = 'CHANGE IN Q COLLECTION DROPLETS BY GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PGSACW'
longname = 'CONVERSION Q TO GRAUPEL DUE TO COLLECTION DROPLETS BY SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRD'
longname = 'DEP CLOUD ICE'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRCI'
longname = 'CHANGE Q AUTOCONVERSION CLOUD ICE BY SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRAI'
longname = 'CHANGE Q ACCRETION CLOUD ICE'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QMULTR'
longname = 'CHANGE Q DUE TO ICE RAIN/SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QMULTRG'
longname = 'CHANGE Q DUE TO ICE MULT RAIN/GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'MNUCCD'
longname = 'CHANGE Q FREEZING AEROSOL (PRIM ICE NUCLEATION)'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRACI'
longname = 'CHANGE QI, ICE-RAIN COLLECTION'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRACIS'
longname = 'CHANGE QI, ICE RAIN COLLISION, ADDED TO SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'EPRD'
longname = 'SUBLIMATION CLOUD ICE'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'MNUCCR'
longname = 'CHANGE Q DUE TO CONTACT FREEZ RAIN'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PIACR'
longname = 'CHANGE QR, ICE-RAIN COLLECTION'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PIACRS'
longname = 'CHANGE QR, ICE RAIN COLLISION, ADDED TO SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PGRACS'
longname = 'CONVERSION Q TO GRAUPEL DUE TO COLLECTION RAIN BY SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRDS'
longname = 'DEP OF SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'EPRDS'
longname = 'SUBLIMATION OF SNOW'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PSACR'
longname = 'CONVERSION DUE TO COLL OF SNOW BY RAIN'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PRDG'
longname = 'DEP OF GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'EPRDG'
longname = 'SUBLIMATION OF GRAUPEL'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRC1'
longname = 'CHANGE NR AUTOCONVERSION DROPLETS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NRAGG'
longname = 'SELF-COLLECTION OF RAIN'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRACG'
longname = 'CHANGE N COLLECTION RAIN BY GRAUPEL'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSUBR'
longname = 'LOSS OF NR DURING EVAP'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSMLTR'
longname = 'CHANGE N MELTING SNOW TO RAIN'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NGMLTR'
longname = 'CHANGE N MELTING GRAUPEL TO RAIN'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRACS'
longname = 'CHANGE N RAIN-SNOW COLLECTION'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NNUCCR'
longname = 'CHANGE N DUE TO CONTACT FREEZ RAIN'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NIACR'
longname = 'CHANGE N, ICE-RAIN COLLECTION'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NIACRS'
longname = 'CHANGE N, ICE RAIN COLLISION, ADDED TO SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NGRACS'
longname = 'CHANGE N CONVERSION TO GRAUPEL DUE TO COLLECTION RAIN BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSMLTS'
longname = 'CHANGE N MELTING SNOW' 
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSAGG'
longname = 'SELF-COLLECTION OF SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRCI'
longname = 'CHANGE N AUTOCONVERSION CLOUD ICE BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSCNG'
longname = 'CHANGE N CONVERSION TO GRAUPEL DUE TO COLLECTION DROPLETS BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSUBS'
longname = 'LOSS OF NS DURING SUB.'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'PCC'
longname = 'SATURATION ADJUSTMENT'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NNUCCC'
longname = 'CONTACT FREEZING OF CLOUD DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPSACWS'
longname = 'DROPLET ACCRETION BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRA'
longname = 'DROPLET ACCRETION BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRC'
longname = 'DROPLET ACCRETION BY RAIN'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPSACWI'
longname = 'DROPLET ACCRETION BY CLOUD ICE'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPSACWG'
longname = 'COLLECTION OF CLOUD DROPS BY GRAUPEL'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NPRAI'
longname = 'ACCRETION OF CLOUD ICE BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NMULTS'
longname = 'ICE MULT., RIMING OF CLOUD DROPS BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NMULTG'
longname = 'ICE MULT., ACCRETION OF CLOUD DROPS BY GRAUPEL'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NMULTR'
longname = 'ICE MULT., RIMING OF RAIN BY SNOW'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NMULTRG'
longname = 'ICE MULT., ACCRETION OF RAIN BY GRAUPEL'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NNUCCD'
longname = 'PRIMARY ICE NUC., FREEZING OF AEROSOLS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSUBI'
longname = 'LOSS OF ICE DUE TO SUBLIMATION'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NGMLTG'
longname = 'LOSS OF GRUPEL DUE TO MELTING'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NSUBG'
longname = 'LOSS OF GRAUPEL DUE TO SUBLIMATION'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NACT'
longname = 'CLOUD DROP FORMATION BY AEROSOL ACTIVATION'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'SFIX_NR'
longname = 'ADJUST RAIN # FOR LARGE/SMALL DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'SFIX_NC'
longname = 'ADJUST CLOUD # FOR LARGE/SMALL DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'SFIX_NI'
longname = 'ADJUST ICE # FOR LARGE/SMALL DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'SFIX_NS'
longname = 'ADJUST SNOW # FOR LARGE/SMALL DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'SFIX_NG'
longname = 'ADJUST GRAUPEL # FOR LARGE/SMALL DROPS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NFIX_NR'
longname = 'ADJUST RAIN # TO REMOVE NEGATIVE VALUES'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NFIX_NC'
longname = 'ADJUST CLOUD # TO REMOVE NEGATIVE VALUES'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NFIX_NI'
longname = 'ADJUST ICE # TO REMOVE NEGATIVE VALUES'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NFIX_NS'
longname = 'ADJUST SNOW # TO REMOVE NEGATIVE VALUES'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NFIX_NG'
longname = 'ADJUST GRAUPEL # TO REMOVE NEGATIVE VALUES'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NIM_CL'
longname = 'CLIP LARGE ICE NUMBER CONCENTRATIONS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QC_INST'
longname = 'INSTANTANEOUS CHANGES TO QC'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QR_INST'
longname = 'INSTANTANEOUS CHANGES TO QR'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QI_INST'
longname = 'INSTANTANEOUS CHANGES TO QI'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QS_INST'
longname = 'INSTANTANEOUS CHANGES TO QNI'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'QG_INST'
longname = 'INSTANTANEOUS CHANGES TO QG'
units = 'kg/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NC_INST'
longname = 'INSTANTANEOUS CHANGES TO NC'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NR_INST'
longname = 'INSTANTANEOUS CHANGES TO NR'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NI_INST'
longname = 'INSTANTANEOUS CHANGES TO NI'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NS_INST'
longname = 'INSTANTANEOUS CHANGES TO NS'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)

name = 'NG_INST'
longname = 'INSTANTANEOUS CHANGES TO NG'
units = '#/kg/s'
call add_to_namelist(count,microcount,name,longname,units,0)
